### ISSUE TITLE
Reduce output

### ISSUE THREAD

**Issue by AmyAmy** [cleversoap/grunt-esdoc#2]
There is a load of output, such as a complete list of generated files, which i only expect when the verbose flag is on.

Would it be possible to only output a simple "done" (and perhaps the coverage), and use [grunt.verbose.writeln](http://gruntjs.com/api/grunt.log) for the list of files?

**Comment by cleversoap** [comment]
Thanks - this is definitely a good idea! Will get right on it

**Comment by cleversoap** [comment]
It seems that ESDoc itself has issues ([104](https://github.com/esdoc/esdoc/issues/104), [83](https://github.com/esdoc/esdoc/pull/83), [208](https://github.com/esdoc/esdoc/issues/208)) with logging and the developer is thankfully aware, however this means that unless there's a patch to ESDoc I can't really do anything to the output. This appears to also be an issue for [gulp-esdoc](https://github.com/nanopx/gulp-esdoc/) too.

That said, I've come up with a solution that does accomplish what is needed, even if it probably is bad practice.

If I temporarily override `console.log` to capture and parse the output from the call to `esdoc.generate` (and then obviously return it to its original state) then it works as desired. Normally overriding a global, especially one like `console.log`, is unequivocally bad behaviour but I think we're safe in Grunt because:
- Any failure kills the entire grunt process and therefore it won't matter.
- Grunt runs tasks in order so as long as the task reverts the override (finally clause in try/catch) it shouldn't matter for the next task and will only affect the `esdoc` task.
- Without looking at the grunt source code, when I was testing exceptions, it correctly reverted the override anyways when calling `grunt.fail.fatal`

**Comment by cleversoap** [comment]
The output will now be determined by the following:
- **--verbose** will show the output of `esdoc.generate` as before.
- **--verbose** and **--debug** will show the verbose output as well as the debug values from esdoc
- Coverage percentage and number of files covered vs the total number of files will be shown for all modes, if coverage is 100% then `grunt.log.ok` is used, if coverage is not complete then `grunt.log.warn` is used.

**Comment by cleversoap** [comment]
`grunt-esdoc@0.0.3` includes the requested changes, note that this version also requires version 4 or greater of Node

**Comment by AmyAmy** [comment]
Works like charm!

one tiny issue, my coverage is currently reported as
Coverage: 17.89% (158/883)
and the current regex doesn't account for non-integer coverage,
I've made a pull-request with the fix.
